# Generated by Django 6.0 on 2025-12-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('action_type', models.CharField(choices=[('CONTAINMENT', 'Confinement (D3)'), ('CORRECTIVE', 'Corrective (D5)'), ('PREVENTIVE', 'Préventive (D7)')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'A faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Fait'), ('VERIFIED', 'Vérifié')], default='TODO', max_length=20)),
                ('efficacy_rate', models.IntegerField(default=0, help_text="Pourcentage d'efficacité")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Symptôme initial')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Clôturé')], default='OPEN', max_length=20)),
                ('current_step', models.CharField(choices=[('D0', 'D0'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'), ('D6', 'D6'), ('D7', 'D7'), ('D8', 'D8')], default='D0', max_length=2)),
                ('level', models.CharField(choices=[('FACTORY', 'Usine'), ('WORKSHOP', 'Atelier'), ('LINE', 'Ligne')], max_length=20)),
                ('d2_who', models.TextField(blank=True, verbose_name='Qui')),
                ('d2_what', models.TextField(blank=True, verbose_name='Quoi')),
                ('d2_where', models.TextField(blank=True, verbose_name='Où')),
                ('d2_when', models.TextField(blank=True, verbose_name='Quand')),
                ('d2_how', models.TextField(blank=True, verbose_name='Comment')),
                ('d2_how_many', models.TextField(blank=True, verbose_name='Combien')),
                ('d2_why', models.TextField(blank=True, verbose_name='Pourquoi')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='problems/attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('METHOD', 'Méthode'), ('MACHINE', 'Machine'), ('MAN', "Main d'œuvre"), ('MATERIAL', 'Matière'), ('ENVIRONMENT', 'Milieu')], max_length=20)),
                ('is_root', models.BooleanField(default=False)),
                ('why_number', models.IntegerField(default=1, help_text='Niveau dans le 5 Pourquoi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
