# Generated by Django 6.0 on 2025-12-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='detection_method',
            field=models.CharField(blank=True, max_length=255, verbose_name='Méthode de détection'),
        ),
        migrations.AddField(
            model_name='problem',
            name='final_report_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_final_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='immediate_actions_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_immediate_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='impacted_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité impactée'),
        ),
        migrations.AddField(
            model_name='problem',
            name='importance',
            field=models.TextField(blank=True, verbose_name='Importance/Criticité'),
        ),
        migrations.AddField(
            model_name='problem',
            name='non_conformity_type',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Produit'), ('PROCESS', 'Processus'), ('DOC', 'Documentation'), ('RAW_MATERIAL', 'Matière première')], max_length=20, verbose_name='Type de non-conformité'),
        ),
        migrations.AddField(
            model_name='problem',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Preuves / Observations'),
        ),
        migrations.AddField(
            model_name='problem',
            name='operator_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Opérateur'),
        ),
        migrations.AddField(
            model_name='problem',
            name='process_continue',
            field=models.BooleanField(null=True, verbose_name='Laisser le processus continuer ?'),
        ),
        migrations.AddField(
            model_name='problem',
            name='rca_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_rca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='risk_equipment',
            field=models.BooleanField(null=True, verbose_name='Risque équipement ?'),
        ),
        migrations.AddField(
            model_name='problem',
            name='risk_personnel',
            field=models.BooleanField(null=True, verbose_name='Risque personnel ?'),
        ),
        migrations.AddField(
            model_name='problem',
            name='workstation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Poste de travail'),
        ),
    ]
