# Generated by Django 6.0 on 2025-12-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_d2_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='non_conformity_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Type de non-conformité'),
        ),
    ]
