# Generated by Django 6.0 on 2025-12-28 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_non_conformity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='root_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='problems.rootcause'),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='analysis_method',
            field=models.CharField(choices=[('5P', '5 Pourquoi'), ('ISHIKAWA', 'Ishikawa'), ('OTHER', 'Autre')], default='5P', max_length=20, verbose_name="Méthode d'analyse"),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='details',
            field=models.TextField(blank=True, verbose_name='Explication détaillée'),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='category',
            field=models.CharField(choices=[('METHOD', 'Méthode'), ('MACHINE', 'Machine'), ('MAN', "Main d'œuvre"), ('MATERIAL', 'Matière'), ('ENVIRONMENT', 'Milieu'), ('MEASURE', 'Mesure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='description',
            field=models.TextField(verbose_name='Cause racine'),
        ),
    ]
