# Generated by Django 6.0 on 2025-12-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_action_root_cause_rootcause_analysis_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcause',
            name='other_method',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autre méthode'),
        ),
    ]
