# Generated by Django 6.0 on 2025-12-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_rootcause_other_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='efficacy_rate',
        ),
    ]
