# Generated by Django 6.0 on 2025-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_remove_action_efficacy_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='containment_actions',
            field=models.TextField(blank=True, verbose_name='Actions de sécurisation (D3)'),
        ),
    ]
