# Generated by Django 6.0 on 2025-12-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_containment_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='line_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ligne'),
        ),
        migrations.AddField(
            model_name='problem',
            name='plant',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usine'),
        ),
        migrations.AddField(
            model_name='problem',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atelier'),
        ),
    ]
