# Generated by Django 6.0 on 2025-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Opérateur'), ('TEAM_LEADER', "Chef d'équipe"), ('SUPERVISOR', 'Superviseur'), ('RESPONSABLE', 'Responsable'), ('MANAGER', 'Manager')], default='OPERATOR', max_length=20),
        ),
    ]
