# Generated by Django 6.0 on 2025-12-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('QUALITY', 'Qualité'), ('PRODUCTION', 'Production'), ('MAINTENANCE', 'Maintenance'), ('LOGISTICS', 'Logistique'), ('ENGINEERING', 'Ingénierie'), ('HR', 'Ressources Humaines'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Département/Service'),
        ),
    ]
