# Generated by Django 6.0 on 2025-12-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('QUALITY', 'Qualité'), ('PRODUCTION', 'Production'), ('MAINTENANCE', 'Maintenance'), ('LOGISTICS', 'Logistique'), ('ENGINEERING', 'Ingénierie'), ('CONTINUOUS_IMPROVEMENT', 'Amélioration Continue'), ('HR', 'Ressources Humaines'), ('OTHER', 'Autre')], default='OTHER', max_length=50, verbose_name='Département/Service'),
        ),
    ]
